/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Next.js Functional API
 * Modern Next.js API with Zod schemas and functional OpenAPI generation
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../app/lib/api/sdk-mutator';
/**
 * Component health status
 */
export type HealthResponseStatus =
  (typeof HealthResponseStatus)[keyof typeof HealthResponseStatus];

export const HealthResponseStatus = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy'
} as const;

/**
 * Component health status
 */
export type ComponentHealthStatus =
  (typeof ComponentHealthStatus)[keyof typeof ComponentHealthStatus];

export const ComponentHealthStatus = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy'
} as const;

/**
 * Additional details
 */
export type ComponentHealthDetails = { [key: string]: unknown | null };

export interface ComponentHealth {
  /** Component health status */
  status: ComponentHealthStatus;
  /** Health check message */
  message: string;
  /** Response time in ms */
  responseTime?: number;
  /** Additional details */
  details?: ComponentHealthDetails;
}

/**
 * Component-specific health checks
 */
export type HealthResponseChecks = { [key: string]: ComponentHealth };

export interface HealthResponse {
  /** Component health status */
  status: HealthResponseStatus;
  /** Current timestamp */
  timestamp: string;
  /** Service version */
  version?: string;
  /** Server uptime in seconds */
  uptime?: number;
  /** Component-specific health checks */
  checks?: HealthResponseChecks;
}

export interface User {
  /** User ID */
  _id: string;
  /**
   * User full name
   * @minLength 1
   */
  name: string;
  /** User email address */
  email: string;
  /**
   * Creation timestamp
   * @nullable
   */
  createdAt: string | null;
  /**
   * Last update timestamp
   * @nullable
   */
  updatedAt: string | null;
}

export interface UserListResponse {
  success: boolean;
  data: User[];
  /** Total number of users */
  count: number;
}

export interface UserResponse {
  success: boolean;
  data: User;
  message?: string;
}

export interface CreateUserRequest {
  /**
   * User full name
   * @minLength 1
   */
  name: string;
  /** User email address */
  email: string;
}

export type GetApiHealth400 = {
  success: boolean;
  error: string;
};

export type GetApiHealth404 = {
  success: boolean;
  error: string;
};

export type GetApiHealth500 = {
  success: boolean;
  error: string;
};

export type GetApiUsers400 = {
  success: boolean;
  error: string;
};

export type GetApiUsers404 = {
  success: boolean;
  error: string;
};

export type GetApiUsers500 = {
  success: boolean;
  error: string;
};

export type PostApiUsers400 = {
  success: boolean;
  error: string;
};

export type PostApiUsers404 = {
  success: boolean;
  error: string;
};

export type PostApiUsers500 = {
  success: boolean;
  error: string;
};

/**
 * Check the overall health status of the API and its dependencies. Optionally check specific components.
 * @summary Health check endpoint
 */
export type getApiHealthResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type getApiHealthResponse400 = {
  data: GetApiHealth400;
  status: 400;
};

export type getApiHealthResponse404 = {
  data: GetApiHealth404;
  status: 404;
};

export type getApiHealthResponse500 = {
  data: GetApiHealth500;
  status: 500;
};

export type getApiHealthResponse503 = {
  data: HealthResponse;
  status: 503;
};

export type getApiHealthResponseSuccess = getApiHealthResponse200 & {
  headers: Headers;
};
export type getApiHealthResponseError = (
  | getApiHealthResponse400
  | getApiHealthResponse404
  | getApiHealthResponse500
  | getApiHealthResponse503
) & {
  headers: Headers;
};

export type getApiHealthResponse =
  | getApiHealthResponseSuccess
  | getApiHealthResponseError;

export const getGetApiHealthUrl = () => {
  return `/api/health`;
};

export const getApiHealth = async (
  options?: RequestInit
): Promise<getApiHealthResponse> => {
  return customInstance<getApiHealthResponse>(getGetApiHealthUrl(), {
    ...options,
    method: 'GET'
  });
};

export const getGetApiHealthQueryKey = () => {
  return [`/api/health`] as const;
};

export const getGetApiHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = GetApiHealth400 | GetApiHealth404 | GetApiHealth500 | HealthResponse
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({
    signal
  }) => getApiHealth({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiHealth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiHealthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiHealth>>
>;
export type GetApiHealthQueryError =
  | GetApiHealth400
  | GetApiHealth404
  | GetApiHealth500
  | HealthResponse;

export function useGetApiHealth<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = GetApiHealth400 | GetApiHealth404 | GetApiHealth500 | HealthResponse
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealth<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = GetApiHealth400 | GetApiHealth404 | GetApiHealth500 | HealthResponse
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealth<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = GetApiHealth400 | GetApiHealth404 | GetApiHealth500 | HealthResponse
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health check endpoint
 */

export function useGetApiHealth<
  TData = Awaited<ReturnType<typeof getApiHealth>>,
  TError = GetApiHealth400 | GetApiHealth404 | GetApiHealth500 | HealthResponse
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve a list of all users in the system
 * @summary Get all users
 */
export type getApiUsersResponse200 = {
  data: UserListResponse;
  status: 200;
};

export type getApiUsersResponse400 = {
  data: GetApiUsers400;
  status: 400;
};

export type getApiUsersResponse404 = {
  data: GetApiUsers404;
  status: 404;
};

export type getApiUsersResponse500 = {
  data: GetApiUsers500;
  status: 500;
};

export type getApiUsersResponseSuccess = getApiUsersResponse200 & {
  headers: Headers;
};
export type getApiUsersResponseError = (
  | getApiUsersResponse400
  | getApiUsersResponse404
  | getApiUsersResponse500
) & {
  headers: Headers;
};

export type getApiUsersResponse =
  | getApiUsersResponseSuccess
  | getApiUsersResponseError;

export const getGetApiUsersUrl = () => {
  return `/api/users`;
};

export const getApiUsers = async (
  options?: RequestInit
): Promise<getApiUsersResponse> => {
  return customInstance<getApiUsersResponse>(getGetApiUsersUrl(), {
    ...options,
    method: 'GET'
  });
};

export const getGetApiUsersQueryKey = () => {
  return [`/api/users`] as const;
};

export const getGetApiUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = GetApiUsers400 | GetApiUsers404 | GetApiUsers500
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({
    signal
  }) => getApiUsers({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiUsers>>
>;
export type GetApiUsersQueryError =
  | GetApiUsers400
  | GetApiUsers404
  | GetApiUsers500;

export function useGetApiUsers<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = GetApiUsers400 | GetApiUsers404 | GetApiUsers500
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUsers<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = GetApiUsers400 | GetApiUsers404 | GetApiUsers500
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiUsers<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = GetApiUsers400 | GetApiUsers404 | GetApiUsers500
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all users
 */

export function useGetApiUsers<
  TData = Awaited<ReturnType<typeof getApiUsers>>,
  TError = GetApiUsers400 | GetApiUsers404 | GetApiUsers500
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new user with the provided information
 * @summary Create a new user
 */
export type postApiUsersResponse201 = {
  data: UserResponse;
  status: 201;
};

export type postApiUsersResponse400 = {
  data: PostApiUsers400;
  status: 400;
};

export type postApiUsersResponse404 = {
  data: PostApiUsers404;
  status: 404;
};

export type postApiUsersResponse500 = {
  data: PostApiUsers500;
  status: 500;
};

export type postApiUsersResponseSuccess = postApiUsersResponse201 & {
  headers: Headers;
};
export type postApiUsersResponseError = (
  | postApiUsersResponse400
  | postApiUsersResponse404
  | postApiUsersResponse500
) & {
  headers: Headers;
};

export type postApiUsersResponse =
  | postApiUsersResponseSuccess
  | postApiUsersResponseError;

export const getPostApiUsersUrl = () => {
  return `/api/users`;
};

export const postApiUsers = async (
  createUserRequest: CreateUserRequest,
  options?: RequestInit
): Promise<postApiUsersResponse> => {
  return customInstance<postApiUsersResponse>(getPostApiUsersUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserRequest)
  });
};

export const getPostApiUsersMutationOptions = <
  TError = PostApiUsers400 | PostApiUsers404 | PostApiUsers500,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiUsers>>,
    TError,
    { data: CreateUserRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiUsers>>,
  TError,
  { data: CreateUserRequest },
  TContext
> => {
  const mutationKey = ['postApiUsers'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiUsers>>,
    { data: CreateUserRequest }
  > = props => {
    const { data } = props ?? {};

    return postApiUsers(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiUsers>>
>;
export type PostApiUsersMutationBody = CreateUserRequest;
export type PostApiUsersMutationError =
  | PostApiUsers400
  | PostApiUsers404
  | PostApiUsers500;

/**
 * @summary Create a new user
 */
export const usePostApiUsers = <
  TError = PostApiUsers400 | PostApiUsers404 | PostApiUsers500,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiUsers>>,
      TError,
      { data: CreateUserRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postApiUsers>>,
  TError,
  { data: CreateUserRequest },
  TContext
> => {
  return useMutation(getPostApiUsersMutationOptions(options), queryClient);
};
